// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuwzicslfywfwhiewrge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1d3ppY3NsZnl3ZndoaWV3cmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDE1MzMsImV4cCI6MjA2NTA3NzUzM30.FQVr_8Xwapa3rEm5yLYDGsLR66vI4sYTaKP222Fd0k0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);